package TestCases;
import java.io.IOException;
import org.testng.Assert;
import org.testng.annotations.Test;
import com.payroll.BaseClass.BaseClass;
import com.payroll.PageObjects.ClientPage;
import com.payroll.PageObjects.CreateClientPage;
import com.payroll.PageObjects.CreateWorkerPage;
import com.payroll.PageObjects.LoginPage;
import com.payroll.PageObjects.WorkerPage;
import com.payroll.Utilities.ExcelRead;
import com.payroll.Utilities.Log;
public class CreateWorkerTest extends BaseClass {
	@Test
	public void createNewWorker() throws IOException, InterruptedException {
		Log.startTestCase("Login To Payroll");
		LoginPage Lg = new LoginPage(getDriver());
		Lg.loginfnt();
		WorkerPage wp = new WorkerPage(getDriver());
		wp.Workers().click();
		wp.CreateWorker().click();
		CreateWorkerPage cwp = new CreateWorkerPage(getDriver());
		Log.info("Start To Enter Client Details");
		act.click(getDriver(), cwp.Title());
		act.selectByIndex(cwp.Title(), 1);
		act.click(getDriver(), cwp.Gender());
		act.selectByIndex(cwp.Gender(), 1);
		act.click(getDriver(), cwp.Division());
		act.selectByIndex(cwp.Division(), 1);
		act.click(getDriver(), cwp.Employementtype());
		act.selectByIndex(cwp.Employementtype(), 1);
		act.click(getDriver(), cwp.Payslip());
		act.selectByIndex(cwp.Payslip(), 1);
		act.click(getDriver(), cwp.Status());
		act.selectByIndex(cwp.Status(), 1);
		act.click(getDriver(), cwp.Firstname());
		String s = ExcelRead.readStringData(10, 0);
		act.type(cwp.Firstname(), s);
		act.click(getDriver(), cwp.Middilename());
		String s1 = ExcelRead.readStringData(10, 1);
		act.type(cwp.Middilename(), s1);
		act.click(getDriver(), cwp.Lastname());
		String s2 = ExcelRead.readStringData(4, 1);
		act.type(cwp.Lastname(), s2);
		act.click(getDriver(), cwp.Dob());
		String s13 = ExcelRead.readIntegerData(3, 1);
		act.type(cwp.Dob(), s13);
		act.click(getDriver(), cwp.Known());
		String s3 = ExcelRead.readStringData(2, 0);
		act.type(cwp.Known(), s3);
		act.click(getDriver(), cwp.Addressline1());
		String s4 = ExcelRead.readStringData(6, 0);
		act.type(cwp.Addressline1(), s4);
		act.click(getDriver(), cwp.Addressline2());
		String s5 = ExcelRead.readStringData(2, 0);
		act.type(cwp.Addressline2(), s5);
		act.click(getDriver(), cwp.Phone());
		String s6 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Phone(), s6);
		act.click(getDriver(), cwp.Addressline3());
		String s7 = ExcelRead.readStringData(1, 0);
		act.type(cwp.Addressline3(), s7);
		act.click(getDriver(), cwp.Mobile());
		String s8 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Mobile(), s8);
		act.click(getDriver(), cwp.Email());
		String s9 = ExcelRead.readStringData(7, 1);
		act.type(cwp.Email(), s9);
		act.click(getDriver(), cwp.Ninumber());
		String s10 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Ninumber(), s10);
		act.click(getDriver(), cwp.Postcode());
		String s11 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Postcode(), s11);
		act.click(getDriver(), cwp.Country());
		String s12 = ExcelRead.readStringData(9, 0);
		act.type(cwp.Country(), s12);
		act.click(getDriver(), cwp.ButtonNext());
		String actual = "Next";
		String expected = cwp.workerBankDetailsSavebtn();
		System.out.println(expected);
		Assert.assertEquals(actual, expected);
		Log.endTestCase("Login And Assertion Completed");
		Log.endTestCase("End to enter Client Details");
	}

	@Test
	public void withoutFilledMandatoryFields() throws IOException, InterruptedException {
		Log.startTestCase("Login To Payroll");
		LoginPage Lg = new LoginPage(getDriver());
		Lg.loginfnt();
		WorkerPage wp = new WorkerPage(getDriver());
		wp.Workers().click();
		wp.CreateWorker().click();
		CreateWorkerPage cwp = new CreateWorkerPage(getDriver());
		Log.info("Start To Enter Client Details");
		act.click(getDriver(), cwp.Title());
		act.selectByIndex(cwp.Title(), 1);
		act.click(getDriver(), cwp.Gender());
		act.selectByIndex(cwp.Gender(), 1);
		act.click(getDriver(), cwp.Division());
		act.selectByIndex(cwp.Division(), 1);
		act.click(getDriver(), cwp.Employementtype());
		act.selectByIndex(cwp.Employementtype(), 1);
		act.click(getDriver(), cwp.Payslip());
		act.selectByIndex(cwp.Payslip(), 1);
		act.click(getDriver(), cwp.Status());
		act.selectByIndex(cwp.Status(), 1);
		act.click(getDriver(), cwp.Middilename());
		String s1 = ExcelRead.readStringData(10, 1);
		act.type(cwp.Middilename(), s1);
		act.click(getDriver(), cwp.Lastname());
		String s2 = ExcelRead.readStringData(4, 1);
		act.type(cwp.Lastname(), s2);
		act.click(getDriver(), cwp.Known());
		String s3 = ExcelRead.readStringData(2, 0);
		act.type(cwp.Known(), s3);
		act.click(getDriver(), cwp.Addressline1());
		String s4 = ExcelRead.readStringData(6, 0);
		act.type(cwp.Addressline1(), s4);
		act.click(getDriver(), cwp.Addressline2());
		String s5 = ExcelRead.readStringData(2, 0);
		act.type(cwp.Addressline2(), s5);
		act.click(getDriver(), cwp.Phone());
		String s6 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Phone(), s6);
		act.click(getDriver(), cwp.Addressline3());
		String s7 = ExcelRead.readStringData(1, 0);
		act.type(cwp.Addressline3(), s7);
		act.click(getDriver(), cwp.Mobile());
		String s8 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Mobile(), s8);
		act.click(getDriver(), cwp.Email());
		String s9 = ExcelRead.readStringData(7, 1);
		act.type(cwp.Email(), s9);
		act.click(getDriver(), cwp.Ninumber());
		String s10 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Ninumber(), s10);
		act.click(getDriver(), cwp.Postcode());
		String s11 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Postcode(), s11);
		act.click(getDriver(), cwp.Country());
		String s12 = ExcelRead.readStringData(9, 0);
		act.type(cwp.Country(), s12);
		act.click(getDriver(), cwp.ButtonNext());
		String actual = "Create Worker";
		String expected = cwp.Assert();
		System.out.println(expected);
		Assert.assertEquals(actual, expected);
		Log.endTestCase("End to enter Client Details");
	}
	@Test
	public void fillAllMandatoryFields() throws IOException, InterruptedException {
		Log.startTestCase("Login To Payroll");
		LoginPage Lg = new LoginPage(getDriver());
		Lg.loginfnt();
		WorkerPage wp = new WorkerPage(getDriver());
		wp.Workers().click();
		wp.CreateWorker().click();
		CreateWorkerPage cwp = new CreateWorkerPage(getDriver());
		Log.info("Start To Enter Client Details");
		act.click(getDriver(), cwp.Gender());
		act.selectByIndex(cwp.Gender(), 1);
		act.click(getDriver(), cwp.Branch());
		act.selectByIndex(cwp.Branch(), 1);
		act.click(getDriver(), cwp.Division());
		act.selectByIndex(cwp.Division(), 1);
		act.click(getDriver(), cwp.Employementtype());
		act.selectByIndex(cwp.Employementtype(), 1);
		act.click(getDriver(), cwp.Payslip());
		act.selectByIndex(cwp.Payslip(), 1);
		act.click(getDriver(), cwp.Firstname());
		String s = ExcelRead.readStringData(10, 0);
		act.type(cwp.Firstname(), s);
		act.click(getDriver(), cwp.Lastname());
		String s2 = ExcelRead.readStringData(4, 1);
		act.type(cwp.Lastname(), s2);
		act.click(getDriver(), cwp.Dob());
		String s13 = ExcelRead.readIntegerData(3, 1);
		act.type(cwp.Dob(), s13);
		act.scrollByVisibilityOfElement(getDriver(),cwp.ButtonNext());
		act.click(getDriver(), cwp.Addressline1());
		String s4 = ExcelRead.readStringData(6, 0);
		act.type(cwp.Addressline1(), s4);
		act.click(getDriver(), cwp.Phone());
		String s6 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Phone(), s6);
		act.click(getDriver(), cwp.Email());
		String s9 = ExcelRead.readStringData(7, 1);
		act.type(cwp.Email(), s9);
		act.click(getDriver(), cwp.Ninumber());
		String s10 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Ninumber(), s10);
		act.click(getDriver(), cwp.Postcode());
		String s11 = ExcelRead.readIntegerData(5, 1);
		act.type(cwp.Postcode(), s11);
		act.click(getDriver(), cwp.ButtonNext());
		String actual = "Next";
		String expected = cwp.workerBankDetailsSavebtn();
		System.out.println(expected);
		Assert.assertEquals(actual, expected);
		Log.endTestCase("Login And Assertion Completed");
		Log.endTestCase("End to enter Client Details");
	}

}
